canton {
    remote-sequencers.sequencer {
        public-api.port = 5008
        public-api.address = "localhost"
        admin-api.port = 5009
        admin-api.address = "localhost"

    }
    remote-mediators.mediator {
        admin-api.port = 5007
        admin-api.address = "localhost"
    }
}