canton {
  features {
    enable-preview-commands = yes
    enable-testing-commands = yes
  }

  parameters {
    manual-start = no
    non-standard-config = yes
    timeouts.processing.verify-active = 40.seconds
    timeouts.processing.slow-future-warn = 20.seconds
  }

  monitoring.logging.delay-logging-threshold = 40.seconds

  participants {
    participant1 {
      init {
          generate-topology-transactions-and-keys = true
          identity.type = auto
      }

      # Ledger API
      ledger-api {
        # TODO(i29736) Revisit this; we want to avoid users to have to set an exp field in their tokens
        max-token-lifetime = Inf
        # Required for pruning
        admin-token-config.admin-claim=false
        address = "0.0.0.0"
        port = 7001
        user-management-service.additional-admin-user-id = "participant1"
        auth-services = []
        # We need to bump this because we run one stream per user +
        # polling for domain connections which can add up quite a bit
        # once you're around ~100 users.
        rate-limit.max-api-services-queue-size = 80000
        interactive-submission-service {
          enable-verbose-hashing = true
        }
        topology-aware-package-selection {
            enabled = true
            enabled = ${?CANTON_PARTICIPANT_ENABLE_TOPOLOGY_PACKAGE_SELECTION}
        }

      }

      # Admin API (optional)
      admin-api {
        address = "0.0.0.0"
        port = 7002
      }

      # HTTP Ledger API
      http-ledger-api {
        address = "0.0.0.0"
        port = 7575
        path-prefix = "participant1"
      }

      # Health service (gRPC)
      monitoring.grpc-health-server {
        address = "0.0.0.0"
        port = 5063
      }

      # Storage
      storage {
        type = postgres
        config {
          url = "jdbc:postgresql://postgres-participant1:5432/participant"
          user = "canton"
          password = "canton"
          databaseName = "participant"
          currentSchema = "participant"
        }
      }

      sequencer-client {
        acknowledgement-interval = 10m
        maximum-in-flight-event-batches = 50
        use-new-connection-pool = true
        enable-amplification-improvements = true
      }

      parameters {
        initial-protocol-version = 34
      }

      topology {
        broadcast-batch-size = 1
        validate-initial-topology-snapshot = false
      }
    }
  }
}