// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/daml/ledger/api/v2/contract_service.proto

// Protobuf Java Version: 3.25.1
package com.daml.ledger.api.v2;

public final class ContractServiceOuterClass {
  private ContractServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetContractRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.daml.ledger.api.v2.GetContractRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The ID of the contract.
     * Must be a valid LedgerString (as described in ``value.proto``).
     * Required
     * </pre>
     *
     * <code>string contract_id = 1;</code>
     * @return The contractId.
     */
    java.lang.String getContractId();
    /**
     * <pre>
     * The ID of the contract.
     * Must be a valid LedgerString (as described in ``value.proto``).
     * Required
     * </pre>
     *
     * <code>string contract_id = 1;</code>
     * @return The bytes for contractId.
     */
    com.google.protobuf.ByteString
        getContractIdBytes();

    /**
     * <pre>
     * The list of querying parties
     * The stakeholders of the referenced contract must have an intersection with any of these parties
     * to return the result.
     * Optional, if no querying_parties specified, all possible contracts could be returned.
     * </pre>
     *
     * <code>repeated string querying_parties = 2;</code>
     * @return A list containing the queryingParties.
     */
    java.util.List<java.lang.String>
        getQueryingPartiesList();
    /**
     * <pre>
     * The list of querying parties
     * The stakeholders of the referenced contract must have an intersection with any of these parties
     * to return the result.
     * Optional, if no querying_parties specified, all possible contracts could be returned.
     * </pre>
     *
     * <code>repeated string querying_parties = 2;</code>
     * @return The count of queryingParties.
     */
    int getQueryingPartiesCount();
    /**
     * <pre>
     * The list of querying parties
     * The stakeholders of the referenced contract must have an intersection with any of these parties
     * to return the result.
     * Optional, if no querying_parties specified, all possible contracts could be returned.
     * </pre>
     *
     * <code>repeated string querying_parties = 2;</code>
     * @param index The index of the element to return.
     * @return The queryingParties at the given index.
     */
    java.lang.String getQueryingParties(int index);
    /**
     * <pre>
     * The list of querying parties
     * The stakeholders of the referenced contract must have an intersection with any of these parties
     * to return the result.
     * Optional, if no querying_parties specified, all possible contracts could be returned.
     * </pre>
     *
     * <code>repeated string querying_parties = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the queryingParties at the given index.
     */
    com.google.protobuf.ByteString
        getQueryingPartiesBytes(int index);
  }
  /**
   * Protobuf type {@code com.daml.ledger.api.v2.GetContractRequest}
   */
  public static final class GetContractRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.daml.ledger.api.v2.GetContractRequest)
      GetContractRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetContractRequest.newBuilder() to construct.
    private GetContractRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetContractRequest() {
      contractId_ = "";
      queryingParties_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetContractRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.daml.ledger.api.v2.ContractServiceOuterClass.internal_static_com_daml_ledger_api_v2_GetContractRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.daml.ledger.api.v2.ContractServiceOuterClass.internal_static_com_daml_ledger_api_v2_GetContractRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractRequest.class, com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractRequest.Builder.class);
    }

    public static final int CONTRACT_ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object contractId_ = "";
    /**
     * <pre>
     * The ID of the contract.
     * Must be a valid LedgerString (as described in ``value.proto``).
     * Required
     * </pre>
     *
     * <code>string contract_id = 1;</code>
     * @return The contractId.
     */
    @java.lang.Override
    public java.lang.String getContractId() {
      java.lang.Object ref = contractId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contractId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The ID of the contract.
     * Must be a valid LedgerString (as described in ``value.proto``).
     * Required
     * </pre>
     *
     * <code>string contract_id = 1;</code>
     * @return The bytes for contractId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContractIdBytes() {
      java.lang.Object ref = contractId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contractId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int QUERYING_PARTIES_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList queryingParties_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <pre>
     * The list of querying parties
     * The stakeholders of the referenced contract must have an intersection with any of these parties
     * to return the result.
     * Optional, if no querying_parties specified, all possible contracts could be returned.
     * </pre>
     *
     * <code>repeated string querying_parties = 2;</code>
     * @return A list containing the queryingParties.
     */
    public com.google.protobuf.ProtocolStringList
        getQueryingPartiesList() {
      return queryingParties_;
    }
    /**
     * <pre>
     * The list of querying parties
     * The stakeholders of the referenced contract must have an intersection with any of these parties
     * to return the result.
     * Optional, if no querying_parties specified, all possible contracts could be returned.
     * </pre>
     *
     * <code>repeated string querying_parties = 2;</code>
     * @return The count of queryingParties.
     */
    public int getQueryingPartiesCount() {
      return queryingParties_.size();
    }
    /**
     * <pre>
     * The list of querying parties
     * The stakeholders of the referenced contract must have an intersection with any of these parties
     * to return the result.
     * Optional, if no querying_parties specified, all possible contracts could be returned.
     * </pre>
     *
     * <code>repeated string querying_parties = 2;</code>
     * @param index The index of the element to return.
     * @return The queryingParties at the given index.
     */
    public java.lang.String getQueryingParties(int index) {
      return queryingParties_.get(index);
    }
    /**
     * <pre>
     * The list of querying parties
     * The stakeholders of the referenced contract must have an intersection with any of these parties
     * to return the result.
     * Optional, if no querying_parties specified, all possible contracts could be returned.
     * </pre>
     *
     * <code>repeated string querying_parties = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the queryingParties at the given index.
     */
    public com.google.protobuf.ByteString
        getQueryingPartiesBytes(int index) {
      return queryingParties_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(contractId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, contractId_);
      }
      for (int i = 0; i < queryingParties_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, queryingParties_.getRaw(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(contractId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, contractId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < queryingParties_.size(); i++) {
          dataSize += computeStringSizeNoTag(queryingParties_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getQueryingPartiesList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractRequest)) {
        return super.equals(obj);
      }
      com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractRequest other = (com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractRequest) obj;

      if (!getContractId()
          .equals(other.getContractId())) return false;
      if (!getQueryingPartiesList()
          .equals(other.getQueryingPartiesList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CONTRACT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getContractId().hashCode();
      if (getQueryingPartiesCount() > 0) {
        hash = (37 * hash) + QUERYING_PARTIES_FIELD_NUMBER;
        hash = (53 * hash) + getQueryingPartiesList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.daml.ledger.api.v2.GetContractRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.daml.ledger.api.v2.GetContractRequest)
        com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.daml.ledger.api.v2.ContractServiceOuterClass.internal_static_com_daml_ledger_api_v2_GetContractRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.daml.ledger.api.v2.ContractServiceOuterClass.internal_static_com_daml_ledger_api_v2_GetContractRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractRequest.class, com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractRequest.Builder.class);
      }

      // Construct using com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        contractId_ = "";
        queryingParties_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.daml.ledger.api.v2.ContractServiceOuterClass.internal_static_com_daml_ledger_api_v2_GetContractRequest_descriptor;
      }

      @java.lang.Override
      public com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractRequest getDefaultInstanceForType() {
        return com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractRequest build() {
        com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractRequest buildPartial() {
        com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractRequest result = new com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.contractId_ = contractId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          queryingParties_.makeImmutable();
          result.queryingParties_ = queryingParties_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractRequest) {
          return mergeFrom((com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractRequest other) {
        if (other == com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractRequest.getDefaultInstance()) return this;
        if (!other.getContractId().isEmpty()) {
          contractId_ = other.contractId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.queryingParties_.isEmpty()) {
          if (queryingParties_.isEmpty()) {
            queryingParties_ = other.queryingParties_;
            bitField0_ |= 0x00000002;
          } else {
            ensureQueryingPartiesIsMutable();
            queryingParties_.addAll(other.queryingParties_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                contractId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureQueryingPartiesIsMutable();
                queryingParties_.add(s);
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object contractId_ = "";
      /**
       * <pre>
       * The ID of the contract.
       * Must be a valid LedgerString (as described in ``value.proto``).
       * Required
       * </pre>
       *
       * <code>string contract_id = 1;</code>
       * @return The contractId.
       */
      public java.lang.String getContractId() {
        java.lang.Object ref = contractId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          contractId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The ID of the contract.
       * Must be a valid LedgerString (as described in ``value.proto``).
       * Required
       * </pre>
       *
       * <code>string contract_id = 1;</code>
       * @return The bytes for contractId.
       */
      public com.google.protobuf.ByteString
          getContractIdBytes() {
        java.lang.Object ref = contractId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          contractId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The ID of the contract.
       * Must be a valid LedgerString (as described in ``value.proto``).
       * Required
       * </pre>
       *
       * <code>string contract_id = 1;</code>
       * @param value The contractId to set.
       * @return This builder for chaining.
       */
      public Builder setContractId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        contractId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The ID of the contract.
       * Must be a valid LedgerString (as described in ``value.proto``).
       * Required
       * </pre>
       *
       * <code>string contract_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearContractId() {
        contractId_ = getDefaultInstance().getContractId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The ID of the contract.
       * Must be a valid LedgerString (as described in ``value.proto``).
       * Required
       * </pre>
       *
       * <code>string contract_id = 1;</code>
       * @param value The bytes for contractId to set.
       * @return This builder for chaining.
       */
      public Builder setContractIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        contractId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringArrayList queryingParties_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureQueryingPartiesIsMutable() {
        if (!queryingParties_.isModifiable()) {
          queryingParties_ = new com.google.protobuf.LazyStringArrayList(queryingParties_);
        }
        bitField0_ |= 0x00000002;
      }
      /**
       * <pre>
       * The list of querying parties
       * The stakeholders of the referenced contract must have an intersection with any of these parties
       * to return the result.
       * Optional, if no querying_parties specified, all possible contracts could be returned.
       * </pre>
       *
       * <code>repeated string querying_parties = 2;</code>
       * @return A list containing the queryingParties.
       */
      public com.google.protobuf.ProtocolStringList
          getQueryingPartiesList() {
        queryingParties_.makeImmutable();
        return queryingParties_;
      }
      /**
       * <pre>
       * The list of querying parties
       * The stakeholders of the referenced contract must have an intersection with any of these parties
       * to return the result.
       * Optional, if no querying_parties specified, all possible contracts could be returned.
       * </pre>
       *
       * <code>repeated string querying_parties = 2;</code>
       * @return The count of queryingParties.
       */
      public int getQueryingPartiesCount() {
        return queryingParties_.size();
      }
      /**
       * <pre>
       * The list of querying parties
       * The stakeholders of the referenced contract must have an intersection with any of these parties
       * to return the result.
       * Optional, if no querying_parties specified, all possible contracts could be returned.
       * </pre>
       *
       * <code>repeated string querying_parties = 2;</code>
       * @param index The index of the element to return.
       * @return The queryingParties at the given index.
       */
      public java.lang.String getQueryingParties(int index) {
        return queryingParties_.get(index);
      }
      /**
       * <pre>
       * The list of querying parties
       * The stakeholders of the referenced contract must have an intersection with any of these parties
       * to return the result.
       * Optional, if no querying_parties specified, all possible contracts could be returned.
       * </pre>
       *
       * <code>repeated string querying_parties = 2;</code>
       * @param index The index of the value to return.
       * @return The bytes of the queryingParties at the given index.
       */
      public com.google.protobuf.ByteString
          getQueryingPartiesBytes(int index) {
        return queryingParties_.getByteString(index);
      }
      /**
       * <pre>
       * The list of querying parties
       * The stakeholders of the referenced contract must have an intersection with any of these parties
       * to return the result.
       * Optional, if no querying_parties specified, all possible contracts could be returned.
       * </pre>
       *
       * <code>repeated string querying_parties = 2;</code>
       * @param index The index to set the value at.
       * @param value The queryingParties to set.
       * @return This builder for chaining.
       */
      public Builder setQueryingParties(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureQueryingPartiesIsMutable();
        queryingParties_.set(index, value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The list of querying parties
       * The stakeholders of the referenced contract must have an intersection with any of these parties
       * to return the result.
       * Optional, if no querying_parties specified, all possible contracts could be returned.
       * </pre>
       *
       * <code>repeated string querying_parties = 2;</code>
       * @param value The queryingParties to add.
       * @return This builder for chaining.
       */
      public Builder addQueryingParties(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureQueryingPartiesIsMutable();
        queryingParties_.add(value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The list of querying parties
       * The stakeholders of the referenced contract must have an intersection with any of these parties
       * to return the result.
       * Optional, if no querying_parties specified, all possible contracts could be returned.
       * </pre>
       *
       * <code>repeated string querying_parties = 2;</code>
       * @param values The queryingParties to add.
       * @return This builder for chaining.
       */
      public Builder addAllQueryingParties(
          java.lang.Iterable<java.lang.String> values) {
        ensureQueryingPartiesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, queryingParties_);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The list of querying parties
       * The stakeholders of the referenced contract must have an intersection with any of these parties
       * to return the result.
       * Optional, if no querying_parties specified, all possible contracts could be returned.
       * </pre>
       *
       * <code>repeated string querying_parties = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearQueryingParties() {
        queryingParties_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The list of querying parties
       * The stakeholders of the referenced contract must have an intersection with any of these parties
       * to return the result.
       * Optional, if no querying_parties specified, all possible contracts could be returned.
       * </pre>
       *
       * <code>repeated string querying_parties = 2;</code>
       * @param value The bytes of the queryingParties to add.
       * @return This builder for chaining.
       */
      public Builder addQueryingPartiesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureQueryingPartiesIsMutable();
        queryingParties_.add(value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.daml.ledger.api.v2.GetContractRequest)
    }

    // @@protoc_insertion_point(class_scope:com.daml.ledger.api.v2.GetContractRequest)
    private static final com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractRequest();
    }

    public static com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetContractRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetContractRequest>() {
      @java.lang.Override
      public GetContractRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GetContractRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetContractRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetContractResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.daml.ledger.api.v2.GetContractResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The representative_package_id will be always set to the contract package ID, therefore this endpoint should
     * not be used to lookup contract which entered the participant via party replication or repair service.
     * The witnesses field will contain only the querying_parties which are also stakeholders of the contract as well.
     * The following fields of the created event cannot be populated, so those should not be used / parsed:
     *
     * - offset
     * - node_id
     * - created_event_blob
     * - interface_views
     * - acs_delta
     *
     * Required
     * </pre>
     *
     * <code>.com.daml.ledger.api.v2.CreatedEvent created_event = 1;</code>
     * @return Whether the createdEvent field is set.
     */
    boolean hasCreatedEvent();
    /**
     * <pre>
     * The representative_package_id will be always set to the contract package ID, therefore this endpoint should
     * not be used to lookup contract which entered the participant via party replication or repair service.
     * The witnesses field will contain only the querying_parties which are also stakeholders of the contract as well.
     * The following fields of the created event cannot be populated, so those should not be used / parsed:
     *
     * - offset
     * - node_id
     * - created_event_blob
     * - interface_views
     * - acs_delta
     *
     * Required
     * </pre>
     *
     * <code>.com.daml.ledger.api.v2.CreatedEvent created_event = 1;</code>
     * @return The createdEvent.
     */
    com.daml.ledger.api.v2.EventOuterClass.CreatedEvent getCreatedEvent();
    /**
     * <pre>
     * The representative_package_id will be always set to the contract package ID, therefore this endpoint should
     * not be used to lookup contract which entered the participant via party replication or repair service.
     * The witnesses field will contain only the querying_parties which are also stakeholders of the contract as well.
     * The following fields of the created event cannot be populated, so those should not be used / parsed:
     *
     * - offset
     * - node_id
     * - created_event_blob
     * - interface_views
     * - acs_delta
     *
     * Required
     * </pre>
     *
     * <code>.com.daml.ledger.api.v2.CreatedEvent created_event = 1;</code>
     */
    com.daml.ledger.api.v2.EventOuterClass.CreatedEventOrBuilder getCreatedEventOrBuilder();
  }
  /**
   * Protobuf type {@code com.daml.ledger.api.v2.GetContractResponse}
   */
  public static final class GetContractResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.daml.ledger.api.v2.GetContractResponse)
      GetContractResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetContractResponse.newBuilder() to construct.
    private GetContractResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetContractResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetContractResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.daml.ledger.api.v2.ContractServiceOuterClass.internal_static_com_daml_ledger_api_v2_GetContractResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.daml.ledger.api.v2.ContractServiceOuterClass.internal_static_com_daml_ledger_api_v2_GetContractResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractResponse.class, com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractResponse.Builder.class);
    }

    private int bitField0_;
    public static final int CREATED_EVENT_FIELD_NUMBER = 1;
    private com.daml.ledger.api.v2.EventOuterClass.CreatedEvent createdEvent_;
    /**
     * <pre>
     * The representative_package_id will be always set to the contract package ID, therefore this endpoint should
     * not be used to lookup contract which entered the participant via party replication or repair service.
     * The witnesses field will contain only the querying_parties which are also stakeholders of the contract as well.
     * The following fields of the created event cannot be populated, so those should not be used / parsed:
     *
     * - offset
     * - node_id
     * - created_event_blob
     * - interface_views
     * - acs_delta
     *
     * Required
     * </pre>
     *
     * <code>.com.daml.ledger.api.v2.CreatedEvent created_event = 1;</code>
     * @return Whether the createdEvent field is set.
     */
    @java.lang.Override
    public boolean hasCreatedEvent() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * The representative_package_id will be always set to the contract package ID, therefore this endpoint should
     * not be used to lookup contract which entered the participant via party replication or repair service.
     * The witnesses field will contain only the querying_parties which are also stakeholders of the contract as well.
     * The following fields of the created event cannot be populated, so those should not be used / parsed:
     *
     * - offset
     * - node_id
     * - created_event_blob
     * - interface_views
     * - acs_delta
     *
     * Required
     * </pre>
     *
     * <code>.com.daml.ledger.api.v2.CreatedEvent created_event = 1;</code>
     * @return The createdEvent.
     */
    @java.lang.Override
    public com.daml.ledger.api.v2.EventOuterClass.CreatedEvent getCreatedEvent() {
      return createdEvent_ == null ? com.daml.ledger.api.v2.EventOuterClass.CreatedEvent.getDefaultInstance() : createdEvent_;
    }
    /**
     * <pre>
     * The representative_package_id will be always set to the contract package ID, therefore this endpoint should
     * not be used to lookup contract which entered the participant via party replication or repair service.
     * The witnesses field will contain only the querying_parties which are also stakeholders of the contract as well.
     * The following fields of the created event cannot be populated, so those should not be used / parsed:
     *
     * - offset
     * - node_id
     * - created_event_blob
     * - interface_views
     * - acs_delta
     *
     * Required
     * </pre>
     *
     * <code>.com.daml.ledger.api.v2.CreatedEvent created_event = 1;</code>
     */
    @java.lang.Override
    public com.daml.ledger.api.v2.EventOuterClass.CreatedEventOrBuilder getCreatedEventOrBuilder() {
      return createdEvent_ == null ? com.daml.ledger.api.v2.EventOuterClass.CreatedEvent.getDefaultInstance() : createdEvent_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getCreatedEvent());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getCreatedEvent());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractResponse)) {
        return super.equals(obj);
      }
      com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractResponse other = (com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractResponse) obj;

      if (hasCreatedEvent() != other.hasCreatedEvent()) return false;
      if (hasCreatedEvent()) {
        if (!getCreatedEvent()
            .equals(other.getCreatedEvent())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCreatedEvent()) {
        hash = (37 * hash) + CREATED_EVENT_FIELD_NUMBER;
        hash = (53 * hash) + getCreatedEvent().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.daml.ledger.api.v2.GetContractResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.daml.ledger.api.v2.GetContractResponse)
        com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.daml.ledger.api.v2.ContractServiceOuterClass.internal_static_com_daml_ledger_api_v2_GetContractResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.daml.ledger.api.v2.ContractServiceOuterClass.internal_static_com_daml_ledger_api_v2_GetContractResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractResponse.class, com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractResponse.Builder.class);
      }

      // Construct using com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCreatedEventFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        createdEvent_ = null;
        if (createdEventBuilder_ != null) {
          createdEventBuilder_.dispose();
          createdEventBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.daml.ledger.api.v2.ContractServiceOuterClass.internal_static_com_daml_ledger_api_v2_GetContractResponse_descriptor;
      }

      @java.lang.Override
      public com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractResponse getDefaultInstanceForType() {
        return com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractResponse build() {
        com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractResponse buildPartial() {
        com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractResponse result = new com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractResponse result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.createdEvent_ = createdEventBuilder_ == null
              ? createdEvent_
              : createdEventBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractResponse) {
          return mergeFrom((com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractResponse other) {
        if (other == com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractResponse.getDefaultInstance()) return this;
        if (other.hasCreatedEvent()) {
          mergeCreatedEvent(other.getCreatedEvent());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getCreatedEventFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.daml.ledger.api.v2.EventOuterClass.CreatedEvent createdEvent_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.daml.ledger.api.v2.EventOuterClass.CreatedEvent, com.daml.ledger.api.v2.EventOuterClass.CreatedEvent.Builder, com.daml.ledger.api.v2.EventOuterClass.CreatedEventOrBuilder> createdEventBuilder_;
      /**
       * <pre>
       * The representative_package_id will be always set to the contract package ID, therefore this endpoint should
       * not be used to lookup contract which entered the participant via party replication or repair service.
       * The witnesses field will contain only the querying_parties which are also stakeholders of the contract as well.
       * The following fields of the created event cannot be populated, so those should not be used / parsed:
       *
       * - offset
       * - node_id
       * - created_event_blob
       * - interface_views
       * - acs_delta
       *
       * Required
       * </pre>
       *
       * <code>.com.daml.ledger.api.v2.CreatedEvent created_event = 1;</code>
       * @return Whether the createdEvent field is set.
       */
      public boolean hasCreatedEvent() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * The representative_package_id will be always set to the contract package ID, therefore this endpoint should
       * not be used to lookup contract which entered the participant via party replication or repair service.
       * The witnesses field will contain only the querying_parties which are also stakeholders of the contract as well.
       * The following fields of the created event cannot be populated, so those should not be used / parsed:
       *
       * - offset
       * - node_id
       * - created_event_blob
       * - interface_views
       * - acs_delta
       *
       * Required
       * </pre>
       *
       * <code>.com.daml.ledger.api.v2.CreatedEvent created_event = 1;</code>
       * @return The createdEvent.
       */
      public com.daml.ledger.api.v2.EventOuterClass.CreatedEvent getCreatedEvent() {
        if (createdEventBuilder_ == null) {
          return createdEvent_ == null ? com.daml.ledger.api.v2.EventOuterClass.CreatedEvent.getDefaultInstance() : createdEvent_;
        } else {
          return createdEventBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * The representative_package_id will be always set to the contract package ID, therefore this endpoint should
       * not be used to lookup contract which entered the participant via party replication or repair service.
       * The witnesses field will contain only the querying_parties which are also stakeholders of the contract as well.
       * The following fields of the created event cannot be populated, so those should not be used / parsed:
       *
       * - offset
       * - node_id
       * - created_event_blob
       * - interface_views
       * - acs_delta
       *
       * Required
       * </pre>
       *
       * <code>.com.daml.ledger.api.v2.CreatedEvent created_event = 1;</code>
       */
      public Builder setCreatedEvent(com.daml.ledger.api.v2.EventOuterClass.CreatedEvent value) {
        if (createdEventBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          createdEvent_ = value;
        } else {
          createdEventBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The representative_package_id will be always set to the contract package ID, therefore this endpoint should
       * not be used to lookup contract which entered the participant via party replication or repair service.
       * The witnesses field will contain only the querying_parties which are also stakeholders of the contract as well.
       * The following fields of the created event cannot be populated, so those should not be used / parsed:
       *
       * - offset
       * - node_id
       * - created_event_blob
       * - interface_views
       * - acs_delta
       *
       * Required
       * </pre>
       *
       * <code>.com.daml.ledger.api.v2.CreatedEvent created_event = 1;</code>
       */
      public Builder setCreatedEvent(
          com.daml.ledger.api.v2.EventOuterClass.CreatedEvent.Builder builderForValue) {
        if (createdEventBuilder_ == null) {
          createdEvent_ = builderForValue.build();
        } else {
          createdEventBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The representative_package_id will be always set to the contract package ID, therefore this endpoint should
       * not be used to lookup contract which entered the participant via party replication or repair service.
       * The witnesses field will contain only the querying_parties which are also stakeholders of the contract as well.
       * The following fields of the created event cannot be populated, so those should not be used / parsed:
       *
       * - offset
       * - node_id
       * - created_event_blob
       * - interface_views
       * - acs_delta
       *
       * Required
       * </pre>
       *
       * <code>.com.daml.ledger.api.v2.CreatedEvent created_event = 1;</code>
       */
      public Builder mergeCreatedEvent(com.daml.ledger.api.v2.EventOuterClass.CreatedEvent value) {
        if (createdEventBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            createdEvent_ != null &&
            createdEvent_ != com.daml.ledger.api.v2.EventOuterClass.CreatedEvent.getDefaultInstance()) {
            getCreatedEventBuilder().mergeFrom(value);
          } else {
            createdEvent_ = value;
          }
        } else {
          createdEventBuilder_.mergeFrom(value);
        }
        if (createdEvent_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <pre>
       * The representative_package_id will be always set to the contract package ID, therefore this endpoint should
       * not be used to lookup contract which entered the participant via party replication or repair service.
       * The witnesses field will contain only the querying_parties which are also stakeholders of the contract as well.
       * The following fields of the created event cannot be populated, so those should not be used / parsed:
       *
       * - offset
       * - node_id
       * - created_event_blob
       * - interface_views
       * - acs_delta
       *
       * Required
       * </pre>
       *
       * <code>.com.daml.ledger.api.v2.CreatedEvent created_event = 1;</code>
       */
      public Builder clearCreatedEvent() {
        bitField0_ = (bitField0_ & ~0x00000001);
        createdEvent_ = null;
        if (createdEventBuilder_ != null) {
          createdEventBuilder_.dispose();
          createdEventBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The representative_package_id will be always set to the contract package ID, therefore this endpoint should
       * not be used to lookup contract which entered the participant via party replication or repair service.
       * The witnesses field will contain only the querying_parties which are also stakeholders of the contract as well.
       * The following fields of the created event cannot be populated, so those should not be used / parsed:
       *
       * - offset
       * - node_id
       * - created_event_blob
       * - interface_views
       * - acs_delta
       *
       * Required
       * </pre>
       *
       * <code>.com.daml.ledger.api.v2.CreatedEvent created_event = 1;</code>
       */
      public com.daml.ledger.api.v2.EventOuterClass.CreatedEvent.Builder getCreatedEventBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getCreatedEventFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * The representative_package_id will be always set to the contract package ID, therefore this endpoint should
       * not be used to lookup contract which entered the participant via party replication or repair service.
       * The witnesses field will contain only the querying_parties which are also stakeholders of the contract as well.
       * The following fields of the created event cannot be populated, so those should not be used / parsed:
       *
       * - offset
       * - node_id
       * - created_event_blob
       * - interface_views
       * - acs_delta
       *
       * Required
       * </pre>
       *
       * <code>.com.daml.ledger.api.v2.CreatedEvent created_event = 1;</code>
       */
      public com.daml.ledger.api.v2.EventOuterClass.CreatedEventOrBuilder getCreatedEventOrBuilder() {
        if (createdEventBuilder_ != null) {
          return createdEventBuilder_.getMessageOrBuilder();
        } else {
          return createdEvent_ == null ?
              com.daml.ledger.api.v2.EventOuterClass.CreatedEvent.getDefaultInstance() : createdEvent_;
        }
      }
      /**
       * <pre>
       * The representative_package_id will be always set to the contract package ID, therefore this endpoint should
       * not be used to lookup contract which entered the participant via party replication or repair service.
       * The witnesses field will contain only the querying_parties which are also stakeholders of the contract as well.
       * The following fields of the created event cannot be populated, so those should not be used / parsed:
       *
       * - offset
       * - node_id
       * - created_event_blob
       * - interface_views
       * - acs_delta
       *
       * Required
       * </pre>
       *
       * <code>.com.daml.ledger.api.v2.CreatedEvent created_event = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.daml.ledger.api.v2.EventOuterClass.CreatedEvent, com.daml.ledger.api.v2.EventOuterClass.CreatedEvent.Builder, com.daml.ledger.api.v2.EventOuterClass.CreatedEventOrBuilder> 
          getCreatedEventFieldBuilder() {
        if (createdEventBuilder_ == null) {
          createdEventBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.daml.ledger.api.v2.EventOuterClass.CreatedEvent, com.daml.ledger.api.v2.EventOuterClass.CreatedEvent.Builder, com.daml.ledger.api.v2.EventOuterClass.CreatedEventOrBuilder>(
                  getCreatedEvent(),
                  getParentForChildren(),
                  isClean());
          createdEvent_ = null;
        }
        return createdEventBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.daml.ledger.api.v2.GetContractResponse)
    }

    // @@protoc_insertion_point(class_scope:com.daml.ledger.api.v2.GetContractResponse)
    private static final com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractResponse();
    }

    public static com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetContractResponse>
        PARSER = new com.google.protobuf.AbstractParser<GetContractResponse>() {
      @java.lang.Override
      public GetContractResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GetContractResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetContractResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.daml.ledger.api.v2.ContractServiceOuterClass.GetContractResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_daml_ledger_api_v2_GetContractRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_daml_ledger_api_v2_GetContractRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_daml_ledger_api_v2_GetContractResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_daml_ledger_api_v2_GetContractResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-com/daml/ledger/api/v2/contract_servic" +
      "e.proto\022\026com.daml.ledger.api.v2\032\"com/dam" +
      "l/ledger/api/v2/event.proto\"C\n\022GetContra" +
      "ctRequest\022\023\n\013contract_id\030\001 \001(\t\022\030\n\020queryi" +
      "ng_parties\030\002 \003(\t\"R\n\023GetContractResponse\022" +
      ";\n\rcreated_event\030\001 \001(\0132$.com.daml.ledger" +
      ".api.v2.CreatedEvent2y\n\017ContractService\022" +
      "f\n\013GetContract\022*.com.daml.ledger.api.v2." +
      "GetContractRequest\032+.com.daml.ledger.api" +
      ".v2.GetContractResponseBL\n\026com.daml.ledg" +
      "er.api.v2B\031ContractServiceOuterClass\252\002\026C" +
      "om.Daml.Ledger.Api.V2b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.daml.ledger.api.v2.EventOuterClass.getDescriptor(),
        });
    internal_static_com_daml_ledger_api_v2_GetContractRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_daml_ledger_api_v2_GetContractRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_daml_ledger_api_v2_GetContractRequest_descriptor,
        new java.lang.String[] { "ContractId", "QueryingParties", });
    internal_static_com_daml_ledger_api_v2_GetContractResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_daml_ledger_api_v2_GetContractResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_daml_ledger_api_v2_GetContractResponse_descriptor,
        new java.lang.String[] { "CreatedEvent", });
    com.daml.ledger.api.v2.EventOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
